
version: '3'
services:
  bot:
    build: .
    volumes:
      - .:/bot
    environment:
      - POSTGRES_PASSWORD=777WhyMeLucky777
    depends_on:
        - db
    ports:
      - "8080:8080"
    command: /bin/bash -c "cd /bot && pip3 install -r req.txt && python3 bot.py"

  db:
    ports:
      - "6432:5432"
    image: postgres:13.4
    volumes:
      - /opt/telegram_bot/postgres:/var/lib/postgresql
    environment:
        - POSTGRES_PASSWORD=777WhyMeLucky777
    command: postgres
